### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by vcyw** [vc-awesome/docs-learning#7]
## 编写文档模板

- [x] 编写“工具使用文档”模板，参考↓
  - [GitHub Docs 官网](https://docs.github.com/zh)
  - [Termux 网页](https://github.com/vc-awesome/docs-learning/blob/master/content/os/mobile/app-termux.md)
  - [中文技术文档的写作规范 - 阮一峰](https://github.com/ruanyf/document-style-guide)

## 编写工具使用文档

- [x] #4 
- [x] 小米笔记（官方手册）
- [x] [GitHub.md](https://github.com/vc-awesome/docs-learning/blob/master/content/tools/github.md)（合并“有道云笔记”中的 GitHub.md)
- [x] ﻿MGit.md（有道云笔记）
